Update update-ui-snapshots.yml

diff --git a/.github/workflows/update-ui-snapshots.yml b/.github/workflows/update-ui-snapshots.yml
--- a/.github/workflows/update-ui-snapshots.yml
+++ b/.github/workflows/update-ui-snapshots.yml
@@ -38,16 +38,16 @@ jobs:
       run: find code/messaging/build -type f
 
     # Step to list contents of the reports directory
-    - name: List files in reports directory
-      run: ls -la code/messaging/build/reports || echo "Reports directory not found"
+    - name: List files in outputs directory
+      run: ls -la code/messaging/build/outputs || echo "Ouputs directory not found"
 
     # Step to check if the roborazzi directory exists
     - name: Check for roborazzi directory
-      run: ls -la code/messaging/build/reports/roborazzi || echo "Roborazzi directory not found"
+      run: ls -la code/messaging/build/outputs/roborazzi || echo "Roborazzi directory not found"
 
     # Upload screenshots if the roborazzi directory is found
     - name: Upload screenshots to GitHub Actions Artifacts
       uses: actions/upload-artifact@v3
       with:
         name: screenshots
-        path: code/messaging/build/reports/roborazzi/
+        path: code/messaging/build/outputs/roborazzi/
